import "../blocks/header/header.js";
import "../blocks/contact/contact.js";
import "../blocks/hero/hero.js";
import "../blocks/year/year.js";
import "../blocks/rating/rating.js";
import "../blocks/culture/culture.js";
import "../blocks/reviews/reviews.js";
import "../blocks/service/service.js";
import "../blocks/works/works.js";